---
- name: get debian cloud image versions
  ansible.builtin.uri:
    url: "{{ debian_cloudimage_repo_url }}"
    return_content: true
  register: debian_cloudimage_versions_page
  when: debian_cloudimage_release == "latest"

- name: parse latest debian cloud image version
  ansible.builtin.set_fact:
    debian_cloudimage_release: >-
      {{ debian_cloudimage_versions_page.content.split('</tr>') |
      map('regex_search', '<a href="(\d{8}-\d+)/">', '\1') |
      select() | map('first') | list | last }}
  when: debian_cloudimage_release == "latest"

- name: get debian cloud image urls
  ansible.builtin.uri:
    url: "{{ debian_cloudimage_repo_url }}{{ debian_cloudimage_release }}/"
    return_content: true
  register: debian_cloudimage_images_page

- name: parse debian cloud image filename
  ansible.builtin.set_fact:
    debian_cloudimage_filename: >-
      {{ debian_cloudimage_images_page.content.split('\n') |
      map('regex_search', '<a href="([^\"]*-%s-(daily-)?%s.%s)">' %
        (debian_cloudimage_type, debian_cloudimage_release, debian_cloudimage_format), '\1')
      | select() | first | first }}

- name: construct debian cloud image url
  ansible.builtin.set_fact:
    debian_cloudimage_url: >-
      {{ debian_cloudimage_repo_url }}{{ debian_cloudimage_release }}/{{ debian_cloudimage_filename }}