---
- name: get debian cloud image checksums
  ansible.builtin.uri:
    url: "{{ debian_cloudimage_repo_url }}{{ debian_cloudimage_release }}/SHA512SUMS"
    return_content: true

- name: parse debian cloud image checksum
  ansible.builtin.set_fact:
    debian_cloudimage_checksum: >-
      {{ debian_cloudimage_checksums.content.split('\n') | 
      map('regex_search', '(\w+)  %s' % debian_cloudimage_filename, '\1') | 
      select() | first | first }}