---
- name: get cloudimage checksums
  ansible.builtin.uri:
    url: "{{ linux_cloudimage_repo_url }}{{ linux_cloudimage_release }}/{{ linux_cloudimage_hashtype|upper }}SUMS"
    return_content: true
  register: linux_cloudimage_checksums_file

- name: parse cloud image checksum
  ansible.builtin.set_fact:
    linux_cloudimage_checksum: >-
      {{ linux_cloudimage_checksums_file.content.split('\n') | 
      map('regex_search', '(\w+) [ \*]%s' % linux_cloudimage_filename, '\1') | 
      select() | first | first }}
