---
- name: get cloudimage checksums
  ansible.builtin.uri:
    url: "{{ proxmox_cloudimage_repo_url }}{{ proxmox_cloudimage_release }}/{{ proxmox_cloudimage_hashtype|upper }}SUMS"
    return_content: true
  register: proxmox_cloudimage_checksums_file

- name: parse cloud image checksum
  ansible.builtin.set_fact:
    proxmox_cloudimage_checksum: >-
      {{ proxmox_cloudimage_checksums_file.content.split('\n') | 
      map('regex_search', '(\w+) [ \*]%s' % proxmox_cloudimage_filename, '\1') | 
      select() | first | first }}
